### ISSUE TITLE
[Question] Contribution Guideline

### ISSUE THREAD

**Issue by lengoanhcat** [luoxuhai/pcl.js#12]
Hi Luoxuhai,

I would like to actively contribute into this pcl.js repo. Is there any contribution guideline which I should follow ? Btw, I don't know how to read Chinese texts.

Regards, 

Cat Le

**Comment by luoxuhai** [comment]
I'm writing a contribution guideline and it will be done soon, my english is not good.😅

**Comment by huiyang-rgb** [comment]
目前写的包含pcl库的cpp文件需要用emscripten编译为webassembly，您好，请问这个如何实现？可以给下具体的流程吗？万分感谢！！！
