### ISSUE TITLE
Added RegionGrowing api and passed all the test cases, but failed to run it in browser | 增加了RegionGrowing的扩展，也通过了测试用例，但是浏览器里跑不起来

### ISSUE THREAD

**Issue by whichones-pink** [luoxuhai/pcl.js#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

extension based on 1.16.0

### Current Behavior

When running in browser, all the class we added are not loaded into the PCLCore.
跑在浏览器的时候，暴露出来的一系列类都没加载到PCLCore里面。

![image](https://github.com/luoxuhai/pcl.js/assets/91660678/7de2ab00-7dcf-4a8b-a419-7abd8b311691)

### Expected Behavior

PCLCore should look like the following(pcl.js v1.16.0)
![image](https://github.com/luoxuhai/pcl.js/assets/91660678/37377f1d-f921-4bce-83d1-4ff596fffecb)

### Steps To Reproduce

[check my code here](https://github.com/whichones-pink/pcl.js/tree/feat/regionGrowing)
[diffs](https://github.com/luoxuhai/pcl.js/commit/89bb6504d61c9ba92330d8b20793d01ca5df9edb)
Just build it and use the new-built pcl-core.wasm and pcl.js

**Comment by whichones-pink** [comment]
I made a stupid mistake here that I replaced my node_modules pcl.js and wasm with the new build one. Although my project hot reloaded, the code changes are not detected.
So can I sumbit a PR now?

**Comment by luoxuhai** [comment]
Thanks!
