### ISSUE TITLE
FAIL  tests/VoxelGrid.test.ts

### ISSUE THREAD

**Issue by lengoanhcat** [luoxuhai/pcl.js#20]
### Expected Behavior
PASS  tests/VoxelGrid.test.ts
### Current Behavior
```
FAIL  tests/VoxelGrid.test.ts
  VoxelGrid
    ✕ should downsampling a PointCloud using a VoxelGrid filter (25 ms)

  ● VoxelGrid › should downsampling a PointCloud using a VoxelGrid filter

    ReferenceError: performance is not defined

      41 | function(PCLCore) {
```
### Steps to Reproduce
1. Pull commit 7239f91b04aa07de03aff0aca199d1eb2d1a54c2 (origin/master)
2. npm run build
3. npm run test
### Environment

- **`pcl.js` version**: 1.2.0
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: devcontainer
- **Running Example**: _url_

**Comment by luoxuhai** [comment]
Do you use [performance](https://developer.mozilla.org/en-US/docs/Web/API/Performance) api in your code?

**Comment by lengoanhcat** [comment]
The only place where I can find `performance` is in pcl-core.js (built with `npm run dev`) 
![image](https://user-images.githubusercontent.com/1382227/190167368-c979234b-3486-46c3-8f69-93e15e84d660.png)

**Comment by luoxuhai** [comment]
Try building with `npm run build:js`, then  `npm run test`.

**Comment by luoxuhai** [comment]
Need to upgrade the version of nodejs to v16:

1. `npm install -g n`
2. `n v16.17.0`

**Comment by luoxuhai** [comment]
@lengoanhcat I have fixed this bug: [f85dc3](https://github.com/luoxuhai/pcl.js/commit/f85dc347f712570111f68a6b6d04adedd2dd988d)
