### ISSUE TITLE
开发流程请教

### ISSUE THREAD

**Issue by liuliuliu11** [luoxuhai/pcl.js#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.15.0

### Current Behavior

**我在~/pcl.js/src路径下和~/pcl.js/test路径下执行，出现下列错误，如何解决。因为个人对前端开发完全不了解，pcl.js开发能否补充一个详细的教程。目前环境已经配置好了。**
(base) anyi@anyi-ThinkStation-P720:~/pcl.js/src$ npm run test

> pcl.js@1.15.0 test /home/anyi/pcl.js
> jest

 FAIL  tests/segmentation/MinCutSegmentation.test.ts
  ● Test suite failed to run

    tests/setup-tests.ts:8:8 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8 global.ROOT_DIR = process.env.PWD;
             ~~~~~~~~

 FAIL  tests/search/SearchKdTree.test.ts
  ● Test suite failed to run

    tests/setup-tests.ts:8:8 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8 global.ROOT_DIR = process.env.PWD;
             ~~~~~~~~

 FAIL  tests/filters/VoxelGrid.test.ts
  ● Test suite failed to run

    tests/setup-tests.ts:8:8 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8 global.ROOT_DIR = process.env.PWD;
             ~~~~~~~~

 FAIL  tests/filters/PassThrough.test.ts
  ● Test suite failed to run

    tests/setup-tests.ts:8:8 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8 global.ROOT_DIR = process.env.PWD;
             ~~~~~~~~

### Expected Behavior

as expected

### Steps To Reproduce

none

### Anything else?

none

**Comment by luoxuhai** [comment]
试下把 `global.ROOT_DIR` 改为 `(global as any).ROOT_DIR`

**Comment by liuliuliu11** [comment]
**我按照您的建议修正后，只有小部分test通过，大多数会报错如下：**
 FAIL  tests/filters/VoxelGrid.test.ts
  ● Test suite failed to run

    tests/filters/VoxelGrid.test.ts:8:50 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8     const pcd = fs.readFileSync(path.join(global.ROOT_DIR, `data/${filename}`));
                                                       ~~~~~~~~

 FAIL  tests/filters/UniformSampling.test.ts
  ● Test suite failed to run

    tests/filters/UniformSampling.test.ts:8:50 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    8     const pcd = fs.readFileSync(path.join(global.ROOT_DIR, `data/${filename}`));
                                                       ~~~~~~~~

 FAIL  tests/io/readPCDHeader.test.ts
  ● Test suite failed to run

    tests/io/readPCDHeader.test.ts:23:51 - error TS2339: Property 'ROOT_DIR' does not exist on type 'Global & typeof globalThis'.

    23     const data = fs.readFileSync(path.join(global.ROOT_DIR, `data/ism_test_cat.pcd`));
                                                         ~~~~~~~~

**另外，想请教的是，我还是不太清楚typescript的开发流程，目前我修改了src/modules/registration.ts和bind/registration.cpp文件，足够了么？？接下来如何检查？**

**Comment by liuliuliu11** [comment]
**我知道怎么解决前一个问题了，还想问一下开发流程，修改了src/modules/registration.ts和bind/registration.cpp文件，足够了么？？接下来如何检查？**

**Comment by luoxuhai** [comment]
> **我知道怎么解决前一个问题了，还想问一下开发流程，修改了src/modules/registration.ts和bind/registration.cpp文件，足够了么？？接下来如何检查？**

1. 修改 `bind/registration.cpp` 和 `src/modules/registration.ts`
2. 运行 `npm run build` 编译
3. 在 `tests/registration` 目录下添加测试代码
4. 运行 `npm run test` 测试

**Comment by liuliuliu11** [comment]
非常感谢你的帮忙！！

我想请教：core/pcl/文件下的C++源码是不需要修改的（尽管我想要实现getFinalTransformation等功能），但是需要参考文档[https://github.com/luoxuhai/pcl/blob/wasm/wasm/README.md]编译为WebAssembly，便于pcl.js使用？我之前有按照链接的操作指南完成了，怎么检查我编译WebAssembly是否正确？目前我看到wasm目录下的文件结构正如链接中所示，不知道是否正确？
/src/bind目录下的文件起声明函数链接C++库的作用，而/src/modules/目录下的文件是实现pcl.js的逻辑处理？

**Comment by luoxuhai** [comment]
> wasm

1. `/src/bind` 目录下是 C++ 代码，用于向 JavaScript 暴露 C++ 接口
2. `/src/modules/` 目录下 是 TypeScript 代码，用于封装由 `/src/bind` 暴露的 JavaScript 接口，便于使用。
3. 能够正常运行 `npm run build` 代表 `core/pcl/` 下代码编译的 WebAssembly 正确

**Comment by luoxuhai** [comment]
> 非常感谢你的帮忙！！
> 
> 我想请教：core/pcl/文件下的C++源码是不需要修改的（尽管我想要实现getFinalTransformation等功能），但是需要参考文档[https://github.com/luoxuhai/pcl/blob/wasm/wasm/README.md]编译为WebAssembly，便于pcl.js使用？我之前有按照链接的操作指南完成了，怎么检查我编译WebAssembly是否正确？目前我看到wasm目录下的文件结构正如链接中所示，不知道是否正确？ /src/bind目录下的文件起声明函数链接C++库的作用，而/src/modules/目录下的文件是实现pcl.js的逻辑处理？

1. `/src/bind` 目录下是 C++ 代码，用于向 JavaScript 暴露 C++ 接口
2. `/src/modules/` 目录下 是 TypeScript 代码，用于封装由 `/src/bind` 暴露的 JavaScript 接口，便于使用。
3. 能够正常运行 `npm run build` 代表 `core/pcl/` 下代码编译的 WebAssembly 正确

**Comment by liuliuliu11** [comment]
**大佬，我之前还可以正常测试，现在突然报错，这是怎么回事？**
 FAIL  tests/common/InitializePCL.test.ts
  ● Test suite failed to run

    Cannot find module '../' from 'tests/utils.ts'

    Require stack:
      tests/utils.ts
      tests/setup-tests.ts

      3 | import fs from 'fs';
      4 | import path from 'path';
    > 5 | import * as PCL from '../';
        | ^
      6 |
      7 | export function initPCL() {
      8 |   const wasm = fs.readFileSync(path.join((global as any).ROOT_DIR, 'dist/pcl-core.wasm'));

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (tests/utils.ts:5:1)


Test Suites: 25 failed, 25 total
Tests:       0 total
Snapshots:   0 total
Time:        5.073 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcl.js@1.15.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcl.js@1.15.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anyi/.npm/_logs/2022-11-21T11_08_24_496Z-debug.log

**Comment by liuliuliu11** [comment]
你好，
**pcl.js/src/bind/build/目录下的内容是什么操作生成的？pcl.js/dist目录下的内容是怎么来的？**
我按照**贡献者指南**依次进行了**如下操作**：

1. git clone https://github.com/luoxuhai/pcl.js --recursive --depth 1 --single-branch --branch master

2. 安装 [Emscripten SDK](https://emscripten.org/docs/getting_started/downloadshtml#installation-instructions-using-the-emsdk-recommended) 【通过“**emcc -v**”和“**./emcc hello_world.c**”和“**node -v**”和“**npm -v**”操作验证安装正确】

3. cd pcl.js   &  npm install

4. 参照链接https://github.com/luoxuhai/pcl/blob/wasm/wasm/README.md进行**下载**和**构建**，
下载：
wasm/scripts/setup-deps.sh 【因为flann命名问题，这里出错，所以通过https://github.com/luoxuhai/flann/archive/refs/heads/wasm.zip手动安装的】
构建：
> 构建 Boost  ：wasm/scripts/build-boost.sh
> 构建 FLANN  ：wasm/scripts/build-flann.sh
> 仅构建  ： PCL ：wasm/scripts/build-pcl.sh
5. npm run build:js  & npm run test 进行测试总是报错说wasm有问题，麻烦帮我看看是哪个环节出了问题，拜托。错误如下：
  ● savePCDFile › should save a binary PCD file

    TypeError: wasm function signature contains illegal type

      at pa (wasm:/wasm/00b1e36e:0:929525)
      at ja (wasm:/wasm/00b1e36e:0:839238)
      at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
      at initRuntime (dist/pcl.cjs.js:43:4809)
      at doRun (dist/pcl.cjs.js:43:123284)
      at run (dist/pcl.cjs.js:43:123338)
      at runCaller (dist/pcl.cjs.js:43:123051)
      at removeRunDependency (dist/pcl.cjs.js:43:5256)
      at receiveInstance (dist/pcl.cjs.js:43:6934)
      at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)

  ● savePCDFile › should save a binary PCD file

    TypeError: Cannot read property 'PointCloudPointXYZ' of null

      394 |     constructor(_PT = PointXYZ, _native) {
      395 |         this._PT = _PT;
    > 396 |         this._native = _native !== null && _native !== void 0 ? _native : new __PCLCore__[`PointCloud${_PT.name}`]();
          |                                                                                          ^
      397 |         this.manager = new Manager(this._native);
      398 |     }
      399 |     get isOrganized() {

      at new PointCloud (dist/pcl.cjs.js:396:90)
      at tests/io/savePCDFile.test.ts:14:11
      at tests/io/savePCDFile.test.ts:31:71
      at Object.<anonymous>.__awaiter (tests/io/savePCDFile.test.ts:27:12)
      at Object.<anonymous> (tests/io/savePCDFile.test.ts:5:22)

  ● savePCDFile › should save a binary_compressed PCD file

    TypeError: wasm function signature contains illegal type

      at pa (wasm:/wasm/00b1e36e:0:929525)
      at ja (wasm:/wasm/00b1e36e:0:839238)
      at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
      at initRuntime (dist/pcl.cjs.js:43:4809)
      at doRun (dist/pcl.cjs.js:43:123284)
      at run (dist/pcl.cjs.js:43:123338)
      at runCaller (dist/pcl.cjs.js:43:123051)
      at removeRunDependency (dist/pcl.cjs.js:43:5256)
      at receiveInstance (dist/pcl.cjs.js:43:6934)
      at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)

  ● savePCDFile › should save a binary_compressed PCD file

    TypeError: Cannot read property 'PointCloudPointXYZ' of null

      394 |     constructor(_PT = PointXYZ, _native) {
      395 |         this._PT = _PT;
    > 396 |         this._native = _native !== null && _native !== void 0 ? _native : new __PCLCore__[`PointCloud${_PT.name}`]();
          |                                                                                          ^
      397 |         this.manager = new Manager(this._native);
      398 |     }
      399 |     get isOrganized() {

      at new PointCloud (dist/pcl.cjs.js:396:90)
      at tests/io/savePCDFile.test.ts:14:11
      at tests/io/savePCDFile.test.ts:31:71
      at Object.<anonymous>.__awaiter (tests/io/savePCDFile.test.ts:27:12)
      at Object.<anonymous> (tests/io/savePCDFile.test.ts:5:22)

**Comment by luoxuhai** [comment]
@liuliuliu11 

这是运行 `npm run build:js` 后 `pcl.js/dist` 目录下的内容：
```bash
dist
├── node
│   ├── pcl.cjs.js
│   ├── pcl-core.node.wasm
│   └── pcl.esm.js
├── pcl.cjs.js
├── pcl-core.wasm
├── pcl.d.ts
├── pcl.esm.js
├── pcl.js
├── pcl.min.js
└── visualization
    ├── PointCloudViewer.d.ts
    ├── PointCloudViewer.esm.js
    ├── PointCloudViewer.js
    └── PointCloudViewer.min.js
```

**Comment by luoxuhai** [comment]
@liuliuliu11
打开这个在线开发环境看看：
https://gitpod.io/#https://github.com/luoxuhai/pcl.js

打开后：
1. `npm install`
2. `npm run build:js && npm ru test`

**Comment by liuliuliu11** [comment]
1.  大佬，如果修改src/bind/build下面的pcl-core.wasm和dist下面的pcl-core.wasm有什么区别？
2. 我现在npm run build:js和npm run dev:js没有报错，紧接着跑npm run test 就有问题，只有在npm run build:wasm时候报错，可见还是生成wasm时候有问题，我现在重新git clone pcl.js 库，什么都没更改，执行npm run build:wasm报错。。
3. 大佬，烦请您实现getFinalTransformation和align（para1,para2）,实在课程作业需要，时间紧急，只想看看pcl配准效果，开发对我说太难了，理解流程、学习ts语言。。。并不像一开始想的简单，就是从零开始。

**Comment by liuliuliu11** [comment]
git clone pcl.js 后

**Comment by liuliuliu11** [comment]
大佬，
_0. 大佬，烦请您实现getFinalTransformation和align（para1,para2）,实在课程作业需要，时间紧急，只想看看pcl配准效果，开发对我说太难了，理解流程、学习ts语言。。。并不像一开始想的简单，就是从零开始。_
1. src/bind/build下面的pcl-core.wasm和dist下面的pcl-core.wasm有什么区别？
2. 我重新git clone pcl.js 库，什么都没更改。依次执行了下列命令：
3. **_npm run build:js 或者npm run dev:js  【执行成功】_**
4. **_npm run test 【执行失败】错误如下：_**
 **FAIL  tests/registration/IterativeClosestPoint.test.ts (8.008 s)
  ● IterativeClosestPoint › should to return a registered point cloud

    TypeError: wasm function signature contains illegal type

      at pa (wasm:/wasm/00b1e36e:0:929525)
      at ja (wasm:/wasm/00b1e36e:0:839238)
      at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
      at initRuntime (dist/pcl.cjs.js:43:4809)
      at doRun (dist/pcl.cjs.js:43:123284)
      at run (dist/pcl.cjs.js:43:123338)
      at runCaller (dist/pcl.cjs.js:43:123051)
      at removeRunDependency (dist/pcl.cjs.js:43:5256)
      at receiveInstance (dist/pcl.cjs.js:43:6934)
      at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)

 FAIL  tests/filters/StatisticalOutlierRemoval.test.ts (8.892 s)
  ● StatisticalOutlierRemoval › should filtering a PointCloud using a StatisticalOutlierRemoval filter

    TypeError: wasm function signature contains illegal type

      at pa (wasm:/wasm/00b1e36e:0:929525)
      at ja (wasm:/wasm/00b1e36e:0:839238)
      at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
      at initRuntime (dist/pcl.cjs.js:43:4809)
      at doRun (dist/pcl.cjs.js:43:123284)
      at run (dist/pcl.cjs.js:43:123338)
      at runCaller (dist/pcl.cjs.js:43:123051)
      at removeRunDependency (dist/pcl.cjs.js:43:5256)
      at receiveInstance (dist/pcl.cjs.js:43:6934)
      at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)**
5. **_npm run build:wasm 或者 npm run dev:wasm【执行失败】错误如下：_**
**(base) anyi@anyi-ThinkStation-P720:~/pcl.js$ npm run dev:wasm
/home/anyi/emsdk/upstream/emscripten/cache/sysroot/include/sys/fcntl.h:1:2: warning: redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-W#warnings]
#warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
/home/anyi/pcl.js/core/pcl/wasm/deps/boost/build/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: **error**: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion]
/home/anyi/pcl.js/core/pcl/wasm/deps/boost/build/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
#   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr）**

**Comment by liuliuliu11** [comment]
icp配准效果受限于两个点云的初始距离，align(param0、param1)，没有初始的变换矩阵RT的输入，icp用途大打折扣呀！

**Comment by luoxuhai** [comment]
> 大佬， _0. 大佬，烦请您实现getFinalTransformation和align（para1,para2）,实在课程作业需要，时间紧急，只想看看pcl配准效果，开发对我说太难了，理解流程、学习ts语言。。。并不像一开始想的简单，就是从零开始。_
> 
> 1. src/bind/build下面的pcl-core.wasm和dist下面的pcl-core.wasm有什么区别？
> 2. 我重新git clone pcl.js 库，什么都没更改。依次执行了下列命令：
> 3. **_npm run build:js 或者npm run dev:js  【执行成功】_**
> 4. **_npm run test 【执行失败】错误如下：_**
>    **FAIL  tests/registration/IterativeClosestPoint.test.ts (8.008 s)
>    ● IterativeClosestPoint › should to return a registered point cloud
>    TypeError: wasm function signature contains illegal type
>    at pa (wasm:/wasm/00b1e36e:0:929525)
>    at ja (wasm:/wasm/00b1e36e:0:839238)
>    at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
>    at initRuntime (dist/pcl.cjs.js:43:4809)
>    at doRun (dist/pcl.cjs.js:43:123284)
>    at run (dist/pcl.cjs.js:43:123338)
>    at runCaller (dist/pcl.cjs.js:43:123051)
>    at removeRunDependency (dist/pcl.cjs.js:43:5256)
>    at receiveInstance (dist/pcl.cjs.js:43:6934)
>    at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)
> 
> FAIL tests/filters/StatisticalOutlierRemoval.test.ts (8.892 s) ● StatisticalOutlierRemoval › should filtering a PointCloud using a StatisticalOutlierRemoval filter
> 
> ```
> TypeError: wasm function signature contains illegal type
> 
>   at pa (wasm:/wasm/00b1e36e:0:929525)
>   at ja (wasm:/wasm/00b1e36e:0:839238)
>   at callRuntimeCallbacks (dist/pcl.cjs.js:43:8298)
>   at initRuntime (dist/pcl.cjs.js:43:4809)
>   at doRun (dist/pcl.cjs.js:43:123284)
>   at run (dist/pcl.cjs.js:43:123338)
>   at runCaller (dist/pcl.cjs.js:43:123051)
>   at removeRunDependency (dist/pcl.cjs.js:43:5256)
>   at receiveInstance (dist/pcl.cjs.js:43:6934)
>   at receiveInstantiationResult (dist/pcl.cjs.js:43:7020)**
> ```
> 
> 5. **_npm run build:wasm 或者 npm run dev:wasm【执行失败】错误如下：_**
>    **(base) anyi@anyi-ThinkStation-P720:~/pcl.js$ npm run dev:wasm
>    /home/anyi/emsdk/upstream/emscripten/cache/sysroot/include/sys/fcntl.h:1:2: warning: redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-W#warnings]
>    #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
>    /home/anyi/pcl.js/core/pcl/wasm/deps/boost/build/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: **error**: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion]
>    /home/anyi/pcl.js/core/pcl/wasm/deps/boost/build/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
> 
> # define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast(expr）**

如果只想看看 pcl 配准效果的话可以直接使用 [PCL C++](https://github.com/PointCloudLibrary/pcl) 库，是课程作业需要在网页上实现？

**Comment by liuliuliu11** [comment]
是的，当时看你pcl.js库在开发，当时软件工程需求分析、设计均是前后端贯通的，我负责前端。

**Comment by luoxuhai** [comment]
> 实现getFinalTransformation和align（para1,para2）,

@liuliuliu11 可能得到这周六日才能实现 `getFinalTransformation` 和 `align(para1,para2)` 了, 工作日没时间😂

**Comment by liuliuliu11** [comment]
在线开发环境https://gitpod.io/#https://github.com/luoxuhai/pcl.js下遇到如下问题
首先感谢大佬提供在线平台，目前可开发了。感谢！！！
1. 环境不稳定，会突然出现emcc 失效的问题，如：emcc -v 有正常的输出，一系列操作后，emcc -v【报错】
2. 尝试添加getFinalTransformation函数时，依次

> 修改 bind/registration.cpp 
**.function("getFinalTransformation", &pcl::Registration<PointSource, PointTarget>::getFinalTransformation)**

> 修改src/modules/registration.ts
  **public getFinalTransformation(RTArray: any) {
    this._native.getFinalTransformation(RTArray);
  }**

> npm run build 编译
**success**

> 修改 tests/registration 
    **let finalRT=null;
    icp.getFinalTransformation(finalRT);**

>  npm run test 测试
【报错】
**at UnboundTypeError.<anonymous> (dist/pcl.cjs.js:43:60361)
      at new UnboundTypeError (eval at createNamedFunction (dist/pcl.cjs.js:43:60070), <anonymous>:4:34)
      at throwUnboundTypeError (dist/pcl.cjs.js:43:82190)
      at IterativeClosestPointPointXYZPointXYZ.unboundTypesHandler [as getFinalTransformation] (dist/pcl.cjs.js:43:89377)
      at IterativeClosestPoint.getFinalTransformation (dist/pcl.cjs.js:1282:22)
      at Object.<anonymous> (tests/registration/IterativeClosestPoint.test.ts:21:9)**

**Comment by luoxuhai** [comment]
> 在线开发环境[https://gitpod.io/#https://github.com/luoxuhai/pcl.js下遇到如下问题 首先感谢大佬提供在线平台，目前可开发了。感谢！！！
> 
> 1. 环境不稳定，会突然出现emcc 失效的问题，如：emcc -v 有正常的输出，一系列操作后，emcc -v【报错】需要重新配置环境才行。
> 2. 尝试添加getFinalTransformation函数时，依次
> 
> > 修改 bind/registration.cpp为：
> > .function("getFinalTransformation", &pcl::Registration<PointSource, PointTarget>::getFinalTransformation)
> 
> > 修改src/modules/registration.ts为：
> > public getFinalTransformation() : any {
> > return this._native.getFinalTransformation();
> > }
> 
> > npm run build 编译  【success】
> 
> > 修改 tests/registration为：
> > const finalRT = icp.getFinalTransformation();
> 
> > npm run test 测试 【报错】
> > at UnboundTypeError. (dist/pcl.cjs.js:43:60361)
> > at new UnboundTypeError (eval at createNamedFunction (dist/pcl.cjs.js:43:60070), :4:34)
> > at throwUnboundTypeError (dist/pcl.cjs.js:43:82190)
> > at IterativeClosestPointPointXYZPointXYZ.unboundTypesHandler [as getFinalTransformation] (dist/pcl.cjs.js:43:89377)
> > at IterativeClosestPoint.getFinalTransformation (dist/pcl.cjs.js:1282:22)
> > at Object. (tests/registration/IterativeClosestPoint.test.ts:21:9)
> 
> 目前感觉是bind/registration.cpp这里需要处理一下pcl c++库中返回的Eigen::Matrix 4f 是吗，具体怎么处理呢？

需要向 JS 暴露 `Eigen::Matrix4f` 可以参考文档：https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html

**Comment by liuliuliu11** [comment]
看了https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html之后，我修改/src/bind/registration.cpp为如下[**为了简单测试，这里返回变换矩阵的第一个值**]：
#include <pcl/registration/ia_ransac.h>
#include <pcl/registration/icp.h>
#include <Eigen/Dense>

#include "embind.hpp"

using namespace pcl;
using namespace emscripten;
using namespace Eigen;


**float getFinal(){
  Eigen::Matrix4f RT = pcl::Registration<PointSource, PointTarget>::getFinalTransformation();
  float res = RT(0, 0);
  return res;
}**

#define BIND_Registration(PointSource, PointTarget)                                              
  class_<pcl::Registration<PointSource, PointTarget>>("Registration" #PointSource #PointTarget)   
      .function("hasConverged", &pcl::Registration<PointSource, PointTarget>::hasConverged)       
      .function("getInputSource", &pcl::Registration<PointSource, PointTarget>::getInputSource)   
      .function("getInputTarget", &pcl::Registration<PointSource, PointTarget>::getInputTarget)   
      **.function("getFinalTransformation", &getFinal)**              
**【报错如下】**：
/workspace/pcl.js/src/bind/registration.cpp:13:42: error: unknown type name 'PointSource'; did you mean 'PointSurfel'?
  Eigen::Matrix4f RT = pcl::Registration<PointSource, PointTarget>::getFinalTransformation();
                                         ^~~~~~~~~~~
                                         PointSurfel
/workspace/pcl.js/core/pcl/build/include/pcl-1.12/pcl/impl/point_types.hpp:1839:10: note: 'PointSurfel' declared here
  struct PointSurfel : public _PointSurfel
         ^
/workspace/pcl.js/src/bind/registration.cpp:13:55: error: use of undeclared identifier 'PointTarget'
  Eigen::Matrix4f RT = pcl::Registration<PointSource, PointTarget>::getFinalTransformation();
                                                      ^
/workspace/pcl.js/src/bind/registration.cpp:13:42: error: unknown type name 'PointSource'; did you mean 'PointSurfel'?
  Eigen::Matrix4f RT = pcl::Registration<PointSource, PointTarget>::getFinalTransformation();
                                         ^~~~~~~~~~~
                                         PointSurfel
/workspace/pcl.js/core/pcl/build/include/pcl-1.12/pcl/impl/point_types.hpp:1839:10: note: 'PointSurfel' declared here
  struct PointSurfel : public _PointSurfel
         ^
/workspace/pcl.js/src/bind/registration.cpp:13:55: error: use of undeclared identifier 'PointTarget'
  Eigen::Matrix4f RT = pcl::Registration<PointSource, PointTarget>::getFinalTransformation();
                                                      ^
In file included from /workspace/pcl.js/src/bind/registration.cpp:5:
In file included from /workspace/pcl.js/src/bind/embind.hpp:8:
/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/bind.h:1630:9: error: implicit instantiation of undefined template 'emscripten::internal::RegisterClassMethod<float (*)()>'
        invoker::template invoke<ClassType, Policies...>(methodName, callable);
        ^
/workspace/pcl.js/src/bind/registration.cpp:105:3: note: in instantiation of function template specialization 'emscripten::class_<pcl::Registration<pcl::PointXYZ, pcl::PointXYZ>>::function<emscripten::internal::DeduceArgumentsTag, float (*)()>' requested here
  BIND_Registration(PointXYZ, PointXYZ);
  ^
/workspace/pcl.js/src/bind/registration.cpp:23:8: note: expanded from macro 'BIND_Registration'
      .function("getFinalTransformation", &getFinal)                                              \
       ^
/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/bind.h:1344:8: note: template is declared here
struct RegisterClassMethod;

**Comment by littlerookie** [comment]
> 

您好，方便说下您当时按照参考文档编译pcl时的系统版本及gcc/g++版本吗，我在编译的时候，使用Ubuntu会报错，提示`Only Windows and POSIX are supported`
